import Head from 'next/head';
type Props = { children: JSX.Element };

export default function Global({ children }: Props) {
  return (
    <>
      <Head>
        <title>Workout App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
}
